.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DS\-ATTRS" "1" "October 2022" ""
.SH "NAME"
\fBds\-attrs\fR \- Print attributes in a dataset\.
.SH "SYNOPSIS"
\fBds attrs\fR [\fIvar\fR] [\fIattr\fR] \fIinput\fR [\fIoptions\fR]
.SH "DESCRIPTION"
The output is formatted as PST \fIhttps://github\.com/peterkuma/pst\fR\.
.SH "ARGUMENTS"
.TP
\fIvar\fR
Variable name or \fBnone\fR to print a dataset attribute \fIattr\fR\. If omitted, print all dataset attributes\.
.TP
\fIattr\fR
Attribute name\.
.TP
\fIinput\fR
Input file\.
.TP
\fIoptions\fR
See help for ds for global options\.
.SH "EXAMPLES"
Print dataset attributes in \fBdataset\.nc\fR\.
.IP "" 4
.nf
$ ds attrs dataset\.nc
title: "Temperature data"
.fi
.IP "" 0
.P
Print attributes of a variable \fBtemperature\fR in \fBdataset\.nc\fR\.
.IP "" 4
.nf
$ ds attrs temperature dataset\.nc
long_name: temperature units: celsius
.fi
.IP "" 0
.P
Print a dataset attribute \fBtitle\fR\.
.IP "" 4
.nf
$ ds attrs none title dataset\.nc
"Temperature data"
.fi
.IP "" 0
.P
Print an attribute units of a variable \fBtemperature\fR\.
.IP "" 4
.nf
$ ds attrs temperature units dataset\.nc
celsius
.fi
.IP "" 0

