.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DS\-CAT" "1" "October 2022" ""
.SH "NAME"
\fBds\-cat\fR \- Print variable data\.
.SH "SYNOPSIS"
\fBds cat\fR \fIvar\fR \fIinput\fR [\fIoptions\fR]
.br
\fBds cat\fR \fIvar\fR\|\.\|\.\|\. \fIinput\fR [\fIoptions\fR]
.br
.SH "DESCRIPTION"
Data are printed by the first index, one item per line, formatted as PST \fIhttps://github\.com/peterkuma/pst\fR\-formatted\. If multiple variables are selected, items at a given index from all variables are printed on the same line as an array\. The first line is a header containing a list of variables\. Missing values are printed as empty rows (if printing one single dimensional variable) or as \fBnone\fR\.
.SH "ARGUMENTS"
.TP
\fIvar\fR
Variable name\.
.TP
\fIinput\fR
Input file\.
.TP
\fIoptions\fR
See help for ds for global options\.
.SH "OPTIONS"
.TP
\fB\-h\fR
Print human\-readable values (time as ISO 8601)\.
.TP
\fB\-\-jd\fR
Convert time variables to Julian date (see Aquarius Time \fIhttps://github\.com/peterkuma/aquarius\-time\fR)\.
.SH "EXAMPLES"
Print temperature values in dataset\.nc\.
.IP "" 4
.nf
$ ds cat temperature dataset\.nc
temperature
16\.000000
18\.000000
21\.000000
.fi
.IP "" 0
.P
Print time and temperature values in dataset\.nc\.
.IP "" 4
.nf
$ ds cat time temperature dataset\.nc
time temperature
1 16\.000000
2 18\.000000
3 21\.000000
.fi
.IP "" 0

