.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DS\-LS" "1" "October 2022" ""
.SH "NAME"
\fBds\-ls\fR \- List variables\.
.SH "SYNOPSIS"
\fBds\fR [\fIvar\fR]\|\.\|\.\|\. \fIinput\fR [\fIoptions\fR]
.br
\fBds ls\fR [\fIvar\fR]\|\.\|\.\|\. \fIinput\fR [\fIoptions\fR]
.br
.SH "DESCRIPTION"
Lines in the output are formatted as PST \fIhttps://github\.com/peterkuma/pst\fR\.
.SH "ARGUMENTS"
.TP
\fIvar\fR
Variable name to list\.
.TP
\fIinput\fR
Input file\.
.TP
\fIoptions\fR
See help for ds for global options\.
.SH "OPTIONS"
.TP
\fB\-l\fR
Print a detailed list of variables (name, type and an array of dimensions), preceded with a line with dataset dimensions\.
.TP
\fBa:\fR \fIattrs\fR
Print variable attributes after the variable name and dimensions\. \fIattrs\fR can be a string or an array\.
.SH "EXAMPLES"
Print a list of variables in \fBdataset\.nc\fR\.
.IP "" 4
.nf
$ ds ls dataset\.nc
temperature
time
.fi
.IP "" 0
.P
Print a detailed list of variables in \fBdataset\.nc\fR\.
.IP "" 4
.nf
$ ds ls \-l dataset\.nc
time: 3
temperature float64 { time }
time int64 { time }
.fi
.IP "" 0
.P
Print a list of variables with an attribute \fBunits\fR\.
.IP "" 4
.nf
$ ds ls dataset\.nc a: units
temperature celsius
time s
.fi
.IP "" 0
.P
Print a list of variables with attributes \fBlong_name\fR and \fBunits\fR\.
.IP "" 4
.nf
$ ds ls dataset\.nc a: { long_name units }
temperature temperature celsius
time time s
.fi
.IP "" 0
.P
Print all variables matching a glob "temp*" in \fBdataset\.nc\fR\.
.IP "" 4
.nf
$ ds ls 'temp*' dataset\.nc
temperature
.fi
.IP "" 0

