.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DS\-MERGE" "1" "October 2022" ""
.SH "NAME"
\fBds\-merge\fR \- Merge datasets along a dimension\.
.SH "SYNOPSIS"
\fBds merge\fR \fIdim\fR \fIinput\fR\|\.\|\.\|\. \fIoutput\fR [\fIoptions\fR]
.SH "DESCRIPTION"
Merge datasets along a dimension \fIdim\fR\. If the dimension is not defined in the dataset, merge along a new dimension \fIdim\fR\. If \fInew\fR is \fBnone\fR and \fIdim\fR is not new, variables without the dimension are set with the first occurrence of the variable\. If \fInew\fR is not \fBnone\fR and \fIdim\fR is not new, variables without the dimension dim are merged along a new dimension \fInew\fR\. If variables is not \fBnone\fR, only those variables are merged along a new dimension and other variables are set to the first occurrence of the variable\.
.SH "ARGUMENTS"
.TP
\fIdim\fR
Name of a dimension to merge along\.
.TP
\fIinput\fR
Input file\.
.TP
\fIoutput\fR
Output file\.
.TP
\fIoptions\fR
See help for ds for global options\.
.SH "OPTIONS"
.TP
\fBnew:\fR \fIvalue\fR
Name of a new dimension\.
.TP
\fBvariables:\fR \fB{\fR \fIvalue\fR\|\.\|\.\|\. \fB}\fR
Variables to merge along a new dimension or none for all variables\.
.SH "EXAMPLES"
Write example data to dataset1\.nc\.
.IP "" 4
.nf
$ ds set { time none time { 1 2 3 } long_name: time units: s } { temperature none time { 16\. 18\. 21\. } long_name: temperature units: celsius } title: "Temperature data" none dataset1\.nc
.fi
.IP "" 0
.P
Write example data to dataset2\.nc\.
.IP "" 4
.nf
$ ds set { time none time { 4 5 6 } long_name: time units: s } { temperature none time { 23\. 25\. 28\. } long_name: temperature units: celsius } title: "Temperature data" none dataset2\.nc
.fi
.IP "" 0
.P
Merge dataset1\.nc and dataset2\.nc and write the result to dataset\.nc\.
.IP "" 4
.nf
$ ds merge time dataset1\.nc dataset2\.nc dataset\.nc
.fi
.IP "" 0
.P
Print time and temperature variables in dataset\.nc\.
.IP "" 4
.nf
$ ds cat time temperature dataset\.nc
time temperature
1 16\.000000
2 18\.000000
3 21\.000000
4 23\.000000
5 25\.000000
6 28\.000000
.fi
.IP "" 0

