.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DS\-RM" "1" "October 2022" ""
.SH "NAME"
\fBds\-rm\fR \- Remove variables or attributes\.
.SH "SYNOPSIS"
\fBds rm\fR \fIvar\fR \fIinput\fR \fIoutput\fR [\fIoptions\fR]
.br
\fBds rm\fR \fIvar\fR \fIattr\fR \fIinput\fR \fIoutput\fR [\fIoptions\fR]
.br
.SH "ARGUMENTS"
.TP
\fIvar\fR
Variable name, an array of variable names or \fBnone\fR to remove a dataset attribute\.
.TP
\fIattr\fR
Attribute name or an array of attribute names\.
.TP
\fIinput\fR
Input file\.
.TP
\fIoutput\fR
Output file\.
.TP
\fIoptions\fR
See help for ds for global options\.
.SH "EXAMPLES"
Remove a variable \fBtemperature\fR in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds rm temperature dataset\.nc output\.nc
.fi
.IP "" 0
.P
Remove variables \fBtime\fR and \fBtemperature\fR in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds rm { time temperature } dataset\.nc output\.nc
.fi
.IP "" 0
.P
Remove a dataset attribute \fBtitle\fR in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds rm none title dataset\.nc output\.nc
.fi
.IP "" 0
.P
Remove an attribute \fBunits\fR of a variable \fBtemperature\fR in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds rm temperature units dataset\.nc output\.nc
.fi
.IP "" 0

