.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DS\-RENAME" "1" "October 2022" ""
.SH "NAME"
\fBds\-rename\fR \- Rename variables and attributes\.
.SH "SYNOPSIS"
\fBds rename\fR \fIvars\fR \fIinput\fR \fIoutput\fR [\fIoptions\fR]
.br
\fBds rename\fR \fIvar\fR \fIattrs\fR \fIinput\fR \fIoutput\fR [\fIoptions\fR]
.br
\fBds rename\fR \fB{\fR \fIvar\fR \fIattrs\fR \fB}\fR\|\.\|\.\|\. \fIinput\fR \fIoutput\fR [\fIoptions\fR]
.br
.SH "ARGUMENTS"
.TP
\fIvar\fR
Variable name, or an array of variable names whose attributes to rename, or \fBnone\fR to rename dataset attributes\.
.TP
\fIvars\fR
Pairs of old and new variable names as \fIoldvar\fR\fB:\fR \fInewvar\fR\. If \fInewattr\fR is \fBnone\fR, remove the attribute\.
.TP
\fIattrs\fR
Pairs of old and new attribute names as \fIoldattr\fR\fB:\fR \fInewattr\fR\. If \fInewattr\fR is \fBnone\fR, remove the attribute\.
.TP
\fIinput\fR
Input file\.
.TP
\fIoutput\fR
Output file\.
.TP
\fIoptions\fR
See help for ds for global options\. Note that with this command \fIoptions\fR can only be supplied before the command name or at the end of the command line\.
.SH "EXAMPLES"
Rename variables \fBtime\fR to \fBnewtime\fR and \fBtemperature\fR to \fBnewtemperature\fR in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds rename time: newtime temperature: newtemperature dataset\.nc output\.nc
.fi
.IP "" 0
.P
Rename a dataset attribute \fBtitle\fR to \fBnewtitle\fR in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds rename none title: newtitle dataset\.nc output\.nc
.fi
.IP "" 0
.P
Rename an attribute \fBunits\fR of a variable \fBtemperature\fR to \fBnewunits\fR in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds rename temperature units: newunits dataset\.nc output\.nc
.fi
.IP "" 0

