.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DS\-SET" "1" "October 2022" ""
.SH "NAME"
\fBds\-set\fR \- Set variable data, dimensions and attributes in an existing or new dataset\.
.SH "SYNOPSIS"
\fBds set\fR \fIds_attrs\fR \fIinput\fR \fIoutput\fR [\fIoptions\fR]
.br
\fBds set\fR \fIvar\fR [\fItype\fR [\fIdims\fR [\fIdata\fR]]] [\fIattrs\fR]\|\.\|\.\|\. \fIinput\fR \fIoutput\fR [\fIoptions\fR]
.br
\fBds set\fR \fB{\fR \fIvar\fR [\fItype\fR [\fIdims\fR [\fIdata\fR]]] [\fIattrs\fR]\|\.\|\.\|\. \fB}\fR\|\.\|\.\|\. \fIds_attrs\fR \fIinput\fR \fIoutput\fR [\fIoptions\fR]
.br
.SH "ARGUMENTS"
.TP
\fIvar\fR
Variable name\.
.TP
\fItype\fR
Variable type (\fBstr\fR), or \fBnone\fR to keep the original type if \fIdata\fR is not supplied or autodetect based on \fIdata\fR if \fIdata\fR is supplied\.
.TP
\fIdims\fR
Variable dimension name (if single), an array of variable dimensions (if multiple), \fBnone\fR to keep original dimension or autogenerate if a new variable, or \fB{ }\fR to autogenerate new dimension names\.
.TP
\fIdata\fR
Variable data\. This can be a PST \fIhttps://github\.com/peterkuma/pst\fR\-formatted scalar or an array\. \fBnone\fR values are interpreted as missing values\.
.TP
\fIattrs\fR
Variable attributes or dataset attributes if \fIvar\fR is \fBnone\fR as \fIattr\fR\fB:\fR \fIvalue\fR pairs\.
.TP
\fIds_attrs\fR
Dataset attributes as \fIattr\fR\fB:\fR \fIvalue\fR pairs\.
.TP
\fIinput\fR
Input file or \fBnone\fR for a new file to be created\.
.TP
\fIoutput\fR
Output file\.
.TP
\fIoptions\fR
See help for ds for global options\. Note that with this command \fIoptions\fR can only be supplied before the command name or at the end of the command line\.
.SH "EXAMPLES"
Write variables \fBtime\fR and \fBtemperature\fR to \fBdataset\.nc\fR\.
.IP "" 4
.nf
$ ds set { time none time { 1 2 3 } long_name: time units: s } { temperature none time { 16\. 18\. 21\. } long_name: temperature units: celsius } title: "Temperature data" none dataset\.nc
.fi
.IP "" 0
.P
Set data of a variable \fBtemperature\fR to an array of 16\.0, 18\.0, 21\.0 in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds set temperature none none { 16\. 18\. 21\. } dataset\.nc output\.nc
.fi
.IP "" 0
.P
Set a dimension of a variable \fBtemperature\fR to time, data to an array of 16\.0, 18\.0, 21\.0, its attribute \fBlong_name\fR to "temperature" and \fBunits\fR to "celsius" in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds set temperature none time { 16\. 18\. 21\. } long_name: temperature units: celsius dataset\.nc output\.nc
.fi
.IP "" 0
.P
Set multiple variables in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds set { time none time { 1 2 3 } long_name: time units: s } { temperature none time { 16\. 18\. 21\. } long_name: temperature units: celsius } title: "Temperature data" dataset\.nc output\.nc
.fi
.IP "" 0
.P
Set a dataset attribute \fBnewtitle\fR to \fBNew title\fR in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds set newtitle: "New title" dataset\.nc output\.nc
.fi
.IP "" 0
.P
Set an attribute \fBnewunits\fR of a variable \fBtemperature\fR to \fBK\fR in \fBdataset\.nc\fR and save the output in \fBoutput\.nc\fR\.
.IP "" 4
.nf
$ ds set temperature newunits: K dataset\.nc output\.nc
.fi
.IP "" 0

