.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DS\-SELECT" "1" "October 2022" ""
.SH "NAME"
\fBds\-select\fR \- Select and subset variables\.
.SH "SYNOPSIS"
\fBds select\fR [\fIvar\fR\|\.\|\.\|\.] [\fIsel\fR] \fIinput\fR \fIoutput\fR [\fIoptions\fR]
.SH "DESCRIPTION"
select can also be used to convert between different file formats (\fBds select\fR \fIinput\fR \fIoutput\fR)\.
.SH "ARGUMENTS"
.TP
\fIvar\fR
Variable name\.
.TP
\fIsel\fR
Selector as \fIdim\fR\fB:\fR \fIidx\fR pairs, where \fIdim\fR is a dimension name and \fIidx\fR is an index or a list of indexes as \fB{\fR \fIi\fR\|\.\|\.\|\. \fB}\fR\.
.TP
\fIinput\fR
Input file\.
.TP
\fIoutput\fR
Output file\.
.TP
\fIoptions\fR
See help for ds for global options\. Note that with this command \fIoptions\fR can only be supplied before the command name or at the end of the command line\.
.SH "EXAMPLES"
Write data to dataset\.nc\.
.IP "" 4
.nf
$ ds set { time none time { 1 2 3 } long_name: time units: s } { temperature none time { 16\. 18\. 21\. } long_name: temperature units: celsius } title: "Temperature data" none dataset\.nc
.fi
.IP "" 0
.P
List variables in dataset\.nc\.
.IP "" 4
.nf
$ ds dataset\.nc
temperature
time
.fi
.IP "" 0
.P
Select variable temperature from dataset\.nc and write to temperature\.nc\.
.IP "" 4
.nf
$ ds select temperature dataset\.nc temperature\.nc
.fi
.IP "" 0
.P
List variables in temperature\.nc\.
.IP "" 4
.nf
$ ds temperature\.nc
temperature
.fi
.IP "" 0
.P
Subset by time index 0 and write to 0\.nc\.
.IP "" 4
.nf
$ ds select time: 0 dataset\.nc 0\.nc
.fi
.IP "" 0
.P
Print variables time and temperature in 0\.nc\.
.IP "" 4
.nf
$ ds cat time temperature 0\.nc
time temperature
1 16\.000000
.fi
.IP "" 0
.P
Convert dataset\.nc to JSON\.
.IP "" 4
.nf
$ ds select dataset\.nc dataset\.json
$ cat dataset\.json
{"time": [1, 2, 3], "temperature": [16\.0, 18\.0, 21\.0], "\.": {"\.": {"title": "Temperature data"}, "time": {"long_name": "time", "units": "s", "\.dims": ["time"], "\.size": [3]}, "temperature": {"long_name": "temperature", "units": "celsius "\.dims": ["time"], "\.size": [3]}}}
.fi
.IP "" 0

