.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DS" "1" "August 2022" ""
.SH "NAME"
\fBds\fR \- Tool for reading, writing and modifying dataset files\.
.SH "SYNOPSIS"
\fBds\fR [\fIcmd\fR [\fIargs\fR]]
.br
\fBds \-\-help\fR [\fIcmd\fR]
.br
\fBds \-\-version\fR
.br
.SH "DESCRIPTION"
The command line interface is based on the PST format \fIhttps://github\.com/peterkuma/pst\fR\.
.SH "ARGUMENTS"
.TP
\fIcmd\fR
Command to execute or show help for\. If omitted, \fBds\fR is a shorthand for the command \fBls\fR, with a difference that files with the same name as any available command cannot be listed\. Available commands are listed below\.
.TP
\fIargs\fR
Command arguments and options\.
.SH "OPTIONS"
.TP
\fB\-\-help\fR
Show this help message or help for a command\.
.TP
\fB\-\-version\fR
Print the version number and exit\.
.SH "AVAILABLE COMMANDS"
.TP
\fBattrs\fR
Print attributes in a dataset\.
.TP
\fBcat\fR
Print variable data\.
.TP
\fBdims\fR
Print dimensions of a dataset or a variable\.
.TP
\fBget\fR
Get attribute at a path\.
.TP
\fBls\fR
List variables\.
.TP
\fBmerge\fR
Merge files along a dimension\.
.TP
\fBmeta\fR
Print dataset metadata\.
.TP
\fBrename\fR
Rename variables and attributes\.
.TP
\fBrename_dim\fR
Rename a dimension\.
.TP
\fBrm\fR
Remove variables or attributes\.
.TP
\fBselect\fR
Select and subset variables\.
.TP
\fBset\fR
Set variable data, dimensions and attributes in an existing or new dataset\.
.TP
\fBstats\fR
Print variable statistics\.
.SH "AUTHOR"
Written by Peter Kuma\.
.SH "COPYRIGHT"
Copyright (c) 2019\-2022 Peter Kuma\. This software is distributed under an MIT license\.
