.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DS" "1" "July 2022" ""
.SH "NAME"
\fBds\fR \- Tool for reading, writing and manipulating dataset files\.
.SH "SYNOPSIS"
\fBds\fR [\fIcmd\fR] [\fIoptions\fR]
.br
\fBds \-\-help\fR [\fIcmd\fR]
.br
\fBds \-\-version\fR
.br
.SH "ARGUMENTS"
.TP
\fIcmd\fR
Command to execute or show help for\. If omitted, the command \fBls\fR is assumed\. Available commands are listed below\.
.SH "OPTIONS"
.TP
\fB\-\-help\fR
Show this help message or help for a command\.
.TP
\fB\-\-version\fR
Print version number and exit\.
.SH "AVAILABLE COMMANDS"
.TP
\fBls\fR
List variables\.
.TP
\fBcat\fR
Print variable\.
.TP
\fBget\fR
Get attribute at a path\.
.TP
\fBmerge\fR
Merge files along a dimension\.
.TP
\fBmeta\fR
Print metadata\.
.TP
\fBselect\fR
Select and subset variables\.
.TP
\fBstats\fR
Print variable statistics\.
.TP
\fBwrite\fR
Write dataset to a file\.
.SH "AUTHOR"
Written by Peter Kuma\.
.SH "COPYRIGHT"
Copyright (c) 2019\-2022 Peter Kuma\. This software is distributed under an MIT license\.
