import json
import numpy as np
import re
import ds_format as ds
from ds_format.cmd import set_

def write(*args, **opts):
	'''
	title: write
	caption: "Write dataset to a file."
	usage: {
		"`ds write` *var* [*dims*] *data* [*attrs*]... *input* *output*"
		"`ds write` `{` *var* [*dims*] *data* [*attrs*]... `}`... *ds_attrs* *input* *output*"
	}
	arguments: {{
		*var*: "Variable name."
		*dims*: "List of variable dimensions or `none` for autogenerated."
		*data*: "Variable data. This can be a PST-formatted scalar or an array."
		*attrs*: "Variable attributes as *attr*: *value* pairs."
		*ds_attrs*: "Dataset attributes as *attr*: *value* pairs."
		*output*: "Output file."
	}}
	desc: "`ds write` is a shorthand for `ds set` with *input* set to `none`."
	examples: {{
		"Write variables time and temperature to dataset.nc.":
		"$ ds write { time time { 1 2 3 } long_name: time units: s } { temperature time { 16. 18. 21. } long_name: temperature units: celsius } title: \\"Temperature data\\" dataset.nc"
	}}
	'''
	if len(args) < 1:
		raise UsageError('Invalid number of arguments')
	args1 = args[:-1]
	output = args[-1]
	set_(*(list(args1) + [None, output]), **opts)
